/*
 * oyun-sdk.js v1: connects your game to the Oyun Takımı site. Do not edit this file.
 * Bu dosya oyununu siteye bağlar. Lütfen değiştirme.
 *
 *   OyunSDK.getLanguage()        -> "tr" | "en"
 *   OyunSDK.getPlayer()          -> Promise<{ nickname } | null>   (null = not signed in)
 *   OyunSDK.submitScore(number)  -> Promise<{ saved, best }>
 *   OyunSDK.onPause(fn) / OyunSDK.onResume(fn)
 *   OyunSDK.mode                 -> "platform" (on the site) | "preview" (opened directly)
 */
(function () {
  "use strict";
  var VERSION = 1;
  var inFrame = window.parent !== window;
  var params = new URLSearchParams(location.search);
  var lang = params.get("lang") || ((navigator.language || "tr").slice(0, 2) === "en" ? "en" : "tr");
  if (lang !== "en") lang = "tr";
  var player = null;
  var pending = {};
  var nextId = 1;
  var pauseFns = [];
  var resumeFns = [];

  function emit(list) {
    list.forEach(function (fn) {
      try { fn(); } catch (e) { console.error(e); }
    });
  }

  function post(message) {
    message.oyun = VERSION;
    window.parent.postMessage(message, "*");
  }

  function request(type, extra) {
    return new Promise(function (resolve, reject) {
      var id = nextId++;
      pending[id] = { resolve: resolve, reject: reject };
      var message = { type: type, id: id };
      for (var k in extra) message[k] = extra[k];
      post(message);
      setTimeout(function () {
        if (pending[id]) {
          delete pending[id];
          reject(new Error("OyunSDK: no answer for " + type));
        }
      }, 10000);
    });
  }

  if (inFrame) {
    window.addEventListener("message", function (event) {
      if (event.source !== window.parent) return;
      var msg = event.data;
      if (!msg || msg.oyun !== VERSION) return;
      if (msg.type === "init") {
        if (msg.lang === "tr" || msg.lang === "en") lang = msg.lang;
        player = msg.player || null;
      } else if (msg.type === "reply" && pending[msg.id]) {
        var p = pending[msg.id];
        delete pending[msg.id];
        if (msg.error) p.reject(new Error(msg.error));
        else p.resolve(msg.result);
      } else if (msg.type === "pause") {
        emit(pauseFns);
      } else if (msg.type === "resume") {
        emit(resumeFns);
      }
    });
    post({ type: "ready" });
  } else {
    // Preview mode: the game was opened directly (for example with a local server).
    // Add ?player=Ali to the address to pretend someone is signed in, ?lang=en for English.
    if (params.get("player")) player = { nickname: params.get("player") };
    document.addEventListener("visibilitychange", function () {
      emit(document.hidden ? pauseFns : resumeFns);
    });
    console.info("[OyunSDK] Önizleme modu / preview mode, lang=" + lang);
  }

  function toast(text) {
    var el = document.createElement("div");
    el.textContent = text;
    el.style.cssText =
      "position:fixed;left:50%;bottom:16px;transform:translateX(-50%);z-index:99999;" +
      "background:#222;color:#fff;font:600 13px system-ui,sans-serif;padding:8px 12px;" +
      "border-radius:999px;opacity:.92;pointer-events:none";
    document.body.appendChild(el);
    setTimeout(function () { el.remove(); }, 2500);
  }

  window.OyunSDK = {
    version: VERSION,
    mode: inFrame ? "platform" : "preview",
    getLanguage: function () { return lang; },
    getPlayer: function () {
      return inFrame ? request("getPlayer", {}) : Promise.resolve(player);
    },
    submitScore: function (score) {
      score = Math.floor(Number(score));
      if (!isFinite(score) || score < 0) return Promise.reject(new Error("OyunSDK: score must be a number >= 0"));
      if (inFrame) return request("score", { score: score });
      var best = 0;
      try { best = Number(localStorage.getItem("oyun-preview-best") || 0); } catch (e) {}
      if (score > best) {
        best = score;
        try { localStorage.setItem("oyun-preview-best", String(best)); } catch (e) {}
      }
      toast("Önizleme / preview: " + score + " (en iyi / best " + best + ")");
      return Promise.resolve({ saved: false, best: best });
    },
    onPause: function (fn) { pauseFns.push(fn); },
    onResume: function (fn) { resumeFns.push(fn); },
  };
})();
